# Read the Docs configuration file
# Updated to sync with pyproject.toml dependency groups
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      # Export dependency groups from pyproject.toml and install them
      - uv export --group docs --group science --no-hashes > rtd-requirements.txt
      - uv pip install -r rtd-requirements.txt
      - uv pip install .
      - rm rtd-requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

formats:
  - pdf
  - epub
