# Prometheus configuration for Scientific Computing Agents monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sci-agents'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application metrics (if exposed)
  - job_name: 'sci-agents'
    static_configs:
      - targets: ['sci-agents:8000']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  # Python application metrics
  - job_name: 'python-app'
    static_configs:
      - targets: ['sci-agents:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s
