# Performance Profile: High Performance
# For high-end systems (16+ cores, 32+ GB RAM)

name: "high_performance"
description: "Maximum performance for high-end systems"
recommended_for:
  - "Workstations (16+ cores)"
  - "Servers (32+ GB RAM)"
  - "GPU-accelerated systems"
  - "Cloud instances (large)"

system_requirements:
  min_cpu_cores: 16
  min_memory_gb: 32
  recommended_disk: "NVMe SSD"

# Cache Configuration
cache:
  l1_cache_mb: 500
  l2_cache_mb: 2000
  l3_cache_mb: 8000
  total_cache_mb: 10500
  ttl_hours: 72
  eviction_policy: "arc"
  enable_disk_cache: true
  prefetch_enabled: true
  prefetch_depth: 3
  cache_warming: true
  aggressive_caching: true

# Parallel Execution
parallel:
  max_workers: 32
  thread_pool_size: 64
  process_pool_size: 32
  queue_size: 10000
  enable_parallel: true
  default_mode: "hybrid"
  batch_size: 1000
  enable_load_balancing: true
  enable_work_stealing: true

# Resource Limits
resources:
  max_memory_percent: 85.0
  max_cpu_percent: 95.0
  io_buffer_size_mb: 256
  max_memory_mb: 16384
  enable_throttling: false
  adaptive_throttling: false

# Agent Configuration
agents:
  max_parallel_agents: 16
  agent_timeout_seconds: 900
  enable_orchestration: true
  default_agents: "all"
  enable_agent_pool: true
  agent_pool_size: 32

# Performance Optimizations
optimizations:
  enable_streaming: true
  enable_lazy_loading: false  # Prefer eager loading with memory
  enable_prefetch: true
  enable_batch_processing: true
  enable_compression: true
  enable_incremental_processing: true
  enable_distributed_processing: true
  enable_gpu_acceleration: false  # Placeholder for future
  enable_simd: true
  enable_zero_copy: true

# Monitoring
monitoring:
  enable_profiling: true
  enable_metrics: true
  enable_distributed_tracing: true
  enable_performance_counters: true
  sample_rate: 1.0
  log_level: "DEBUG"
  real_time_dashboard: true

# Expected Performance
expected_performance:
  baseline_duration_seconds: 600
  target_speedup: "10-20x"
  cache_hit_rate_target: 90.0
  throughput_files_per_second: 500
  latency_p50_ms: 5
  latency_p99_ms: 50