# Performance Profile: Large Project
# For codebases with > 10000 files

name: "large_project"
description: "Optimized for large codebases (>10000 files)"
min_files: 10000
recommended_for:
  - "Enterprise applications"
  - "Large frameworks"
  - "Monorepos"
  - "Operating systems"

# Cache Configuration
cache:
  l1_cache_mb: 200
  l2_cache_mb: 1000
  l3_cache_mb: 5000
  total_cache_mb: 6200
  ttl_hours: 48
  eviction_policy: "arc"  # Adaptive replacement cache
  enable_disk_cache: true
  prefetch_enabled: true
  cache_warming: true
  distributed_cache: true

# Parallel Execution
parallel:
  max_workers: 16
  thread_pool_size: 32
  process_pool_size: 16
  queue_size: 5000
  enable_parallel: true
  default_mode: "hybrid"  # Mixed thread/process
  batch_size: 500
  enable_load_balancing: true

# Resource Limits
resources:
  max_memory_percent: 75.0
  max_cpu_percent: 85.0
  io_buffer_size_mb: 128
  max_memory_mb: 8192
  enable_throttling: true
  adaptive_throttling: true

# Agent Configuration
agents:
  max_parallel_agents: 8
  agent_timeout_seconds: 600
  enable_orchestration: true
  default_agents: "all"
  enable_agent_pool: true

# Performance Optimizations
optimizations:
  enable_streaming: true
  enable_lazy_loading: true
  enable_prefetch: true
  enable_batch_processing: true
  enable_compression: true
  enable_incremental_processing: true
  enable_distributed_processing: false

# Monitoring
monitoring:
  enable_profiling: true
  enable_metrics: true
  enable_distributed_tracing: true
  sample_rate: 0.5
  log_level: "DEBUG"

# Expected Performance
expected_performance:
  baseline_duration_seconds: 600
  target_speedup: "8-10x"
  cache_hit_rate_target: 80.0
  throughput_files_per_second: 200