# Performance Profile: Medium Project
# For codebases with 1000-10000 files

name: "medium_project"
description: "Optimized for medium codebases (1000-10000 files)"
min_files: 1000
max_files: 10000
recommended_for:
  - "Medium-sized applications"
  - "Standard libraries"
  - "Corporate projects"

# Cache Configuration
cache:
  l1_cache_mb: 100
  l2_cache_mb: 500
  l3_cache_mb: 2000
  total_cache_mb: 2600
  ttl_hours: 24
  eviction_policy: "lru"
  enable_disk_cache: true
  prefetch_enabled: true
  cache_warming: true

# Parallel Execution
parallel:
  max_workers: 8
  thread_pool_size: 16
  process_pool_size: 8
  queue_size: 1000
  enable_parallel: true
  default_mode: "thread"
  batch_size: 100

# Resource Limits
resources:
  max_memory_percent: 70.0
  max_cpu_percent: 80.0
  io_buffer_size_mb: 64
  max_memory_mb: 2048
  enable_throttling: true

# Agent Configuration
agents:
  max_parallel_agents: 4
  agent_timeout_seconds: 300
  enable_orchestration: true
  default_agents: "core"

# Performance Optimizations
optimizations:
  enable_streaming: true
  enable_lazy_loading: true
  enable_prefetch: true
  enable_batch_processing: true
  enable_compression: true

# Monitoring
monitoring:
  enable_profiling: true
  enable_metrics: true
  sample_rate: 0.2
  log_level: "INFO"

# Expected Performance
expected_performance:
  baseline_duration_seconds: 60
  target_speedup: "5-8x"
  cache_hit_rate_target: 70.0
  throughput_files_per_second: 100