# Performance Profile: Small Project
# For codebases with < 1000 files

name: "small_project"
description: "Optimized for small codebases (<1000 files)"
max_files: 1000
recommended_for:
  - "Personal projects"
  - "Small libraries"
  - "Prototypes"

# Cache Configuration
cache:
  l1_cache_mb: 50
  l2_cache_mb: 100
  l3_cache_mb: 250
  total_cache_mb: 400
  ttl_hours: 12
  eviction_policy: "lru"
  enable_disk_cache: true
  prefetch_enabled: false
  cache_warming: false

# Parallel Execution
parallel:
  max_workers: 4
  thread_pool_size: 8
  process_pool_size: 4
  queue_size: 200
  enable_parallel: true
  default_mode: "thread"
  batch_size: 50

# Resource Limits
resources:
  max_memory_percent: 60.0
  max_cpu_percent: 75.0
  io_buffer_size_mb: 16
  max_memory_mb: 512
  enable_throttling: false

# Agent Configuration
agents:
  max_parallel_agents: 2
  agent_timeout_seconds: 120
  enable_orchestration: false
  default_agents: "core"

# Performance Optimizations
optimizations:
  enable_streaming: false
  enable_lazy_loading: false
  enable_prefetch: false
  enable_batch_processing: true
  enable_compression: false

# Monitoring
monitoring:
  enable_profiling: false
  enable_metrics: true
  sample_rate: 0.1
  log_level: "INFO"

# Expected Performance
expected_performance:
  baseline_duration_seconds: 10
  target_speedup: "3-5x"
  cache_hit_rate_target: 60.0
  throughput_files_per_second: 50