# UX Configuration File
# This file configures the user experience features of the command executor

# Theme Settings
theme: dark  # Options: dark, light, auto
color_enabled: true
animations: true

# Progress Indicators
progress:
  enabled: true
  style: bar  # Options: bar, spinner, dots
  show_percentage: true
  show_time: true
  show_eta: true
  refresh_rate: 10  # Updates per second

# Error Handling
errors:
  show_suggestions: true
  show_stack_trace: true
  show_context: true
  max_context_lines: 5
  auto_recovery: false

# Command Recommendations
recommendations:
  enabled: true
  learn_from_usage: true
  show_confidence: true
  max_suggestions: 5
  workflow_suggestions: true

# Verbosity Levels
# 0 = quiet, 1 = normal, 2 = verbose, 3 = debug
verbosity: 1

# User Interaction
interaction:
  confirmation_prompts: true
  interactive_mode: false
  tutorial_mode: false
  autocomplete: true

# Accessibility
accessibility:
  mode: false  # Disables animations, uses high contrast
  screen_reader_support: false
  color_blind_mode: false
  high_contrast: false

# Output Format
output:
  format: text  # Options: text, json, markdown, html
  width: auto  # Terminal width (auto or number)
  paging: false  # Enable paging for long output

# Dashboard
dashboard:
  enabled: true
  show_resources: true
  show_cache_stats: true
  show_agents: true
  refresh_rate: 4

# Performance
performance:
  cache_enabled: true
  async_updates: true
  background_updates: true
  max_concurrent_tasks: 10

# Logging
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: ~/.claude/logs/ux.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Experimental Features
experimental:
  ml_recommendations: false
  smart_error_recovery: false
  predictive_workflow: false
  voice_feedback: false