# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# Add _ext directory to Python path for custom extensions
sys.path.insert(0, os.path.abspath('_ext'))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Claude Code Plugin Marketplace'
copyright = f'{datetime.now().year}, Wei Chen'
author = 'Wei Chen'
release = '1.0.7'
version = '1.0.7'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',      # Auto-generate documentation from docstrings
    'sphinx.ext.napoleon',     # Support for Google/NumPy style docstrings
    'sphinx.ext.intersphinx',  # Link to other project documentation
    'sphinx.ext.viewcode',     # Add links to highlighted source code
    'sphinx_copybutton',       # Add copy button to code blocks
    'plugin_directives',       # Custom directives for plugin documentation
]

templates_path = ['_templates']
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '.venv/**',  # Exclude virtual environment
]

# The suffix(es) of source filenames
source_suffix = {
    '.rst': 'restructuredtext',
}

# The master document
master_doc = 'index'

# Language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'furo'
html_static_path = ['_static']

# Furo theme options
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#7C3AED",
        "color-brand-content": "#7C3AED",
    },
    "dark_css_variables": {
        "color-brand-primary": "#A78BFA",
        "color-brand-content": "#A78BFA",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_button": "edit",
}

# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = 'ClaudeCodePluginMarketplacedoc'

# -- Extension configuration -------------------------------------------------

# Napoleon settings for Google/NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Intersphinx configuration
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# Copy button configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# -- Options for sphinx-multiversion -----------------------------------------
# Configuration for versioned documentation support

# Whitelist pattern for tags/branches to build
smv_tag_whitelist = r'^v\d+\.\d+\.\d+$'  # Match tags like v1.0.0, v1.1.0
smv_branch_whitelist = r'^(main|master)$'  # Build from main/master branch
smv_remote_whitelist = r'^origin$'  # Only use origin remote

# Output format
smv_latest_version = 'v1.0.7'  # Latest version indicator

# -- Additional Sphinx configuration -----------------------------------------

# Add any custom settings here
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True

# Output file base name for HTML help builder
htmlhelp_basename = 'ClaudeCodePluginMarketplacedoc'

# If true, links to the reST sources are added to the pages
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = True

# If true, the current page is highlighted in the sidebar
# Furo handles sidebars automatically

# Output format
html_use_index = True
html_split_index = False
html_compact_lists = True

# Custom CSS files
# html_css_files = []

# Custom JS files
# html_js_files = []
