name: Validate Multi-Platform Apps Plugin

on:
  push:
    paths:
      - 'plugins/multi-platform-apps/**'
      - '.github/workflows/validate-multi-platform-apps.yml'
  pull_request:
    paths:
      - 'plugins/multi-platform-apps/**'
      - '.github/workflows/validate-multi-platform-apps.yml'

jobs:
  validate-plugin:
    name: Validate Plugin Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Validate plugin structure
        run: |
          cd plugins/multi-platform-apps
          bash scripts/validate-plugin.sh

      - name: Run performance benchmarks
        run: |
          cd plugins/multi-platform-apps
          python3 scripts/benchmark-performance.py

      - name: Check JSON validity
        run: |
          python3 -m json.tool plugins/multi-platform-apps/plugin.json > /dev/null
          echo "✓ plugin.json is valid"

      - name: Validate agent files
        run: |
          echo "Checking agent frontmatter..."
          for agent in plugins/multi-platform-apps/agents/*.md; do
            if head -5 "$agent" | grep -q "^name:"; then
              echo "✓ $(basename "$agent") has valid frontmatter"
            else
              echo "✗ $(basename "$agent") missing frontmatter"
              exit 1
            fi
          done

      - name: Summary
        if: always()
        run: |
          echo "✓ Multi-Platform Apps Plugin validation complete"
          echo "All checks passed successfully"

  performance-analysis:
    name: Performance Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Analyze content size
        run: |
          echo "=== Content Statistics ==="
          echo "Agents:"
          wc -l plugins/multi-platform-apps/agents/*.md
          echo ""
          echo "Total agent documentation:"
          wc -l plugins/multi-platform-apps/agents/*.md | tail -1

      - name: Check performance metadata
        run: |
          if grep -q "performance_optimizations" plugins/multi-platform-apps/plugin.json; then
            echo "✓ Performance optimizations configured"
          else
            echo "⚠ Consider adding performance optimization metadata"
          fi
