name: Link Validation

# Run link validation on documentation changes
on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - 'status/**'
      - 'archive/**'
      - '.github/workflows/link-validation.yml'
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'docs/**'
      - 'status/**'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-internal-links:
    name: Validate Internal Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          # No dependencies needed - script uses stdlib only
          echo "Link checker uses Python stdlib only"

      - name: Run internal link validation
        run: |
          python3 scripts/check_links.py --fast --fix
        continue-on-error: false

      - name: Upload validation results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: link-validation-results
          path: |
            .link_check_cache.json
          retention-days: 7

  validate-external-links:
    name: Validate External Links (Optional)
    runs-on: ubuntu-latest
    # Run external link validation but don't fail the workflow
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requests library
        run: |
          pip install requests

      - name: Restore external link cache
        uses: actions/cache@v3
        with:
          path: .link_check_cache.json
          key: link-cache-${{ github.sha }}
          restore-keys: |
            link-cache-

      - name: Run external link validation
        run: |
          python3 scripts/check_links.py --fix
        continue-on-error: true

      - name: Save external link cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: .link_check_cache.json
          key: link-cache-${{ github.sha }}

      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: external-link-validation-results
          path: |
            .link_check_cache.json
          retention-days: 30

  # Summary job
  link-validation-summary:
    name: Link Validation Summary
    runs-on: ubuntu-latest
    needs: [validate-internal-links]
    if: always()

    steps:
      - name: Check validation results
        run: |
          if [ "${{ needs.validate-internal-links.result }}" == "success" ]; then
            echo "✅ All internal links are valid!"
          else
            echo "❌ Internal link validation failed. Check the logs above."
            exit 1
          fi

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Link Validation Failed**\n\nBroken links detected in documentation. Please run `python3 scripts/check_links.py --fix` locally to identify and fix broken links.\n\nSee the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            })
